"""Initial schema

Revision ID: 13ae27d537ab
Revises: 46be82786ce3
Create Date: 2023-12-07 21:22:33.148415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ae27d537ab'
down_revision = '46be82786ce3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
